import React from "react";
import CategoryProductList from "./CategoryProductList";

const BrakeParts = () => {
  // Brake System Products based on the image
  const products = [
    {
      id: 1,
      name: "ACCESSORY KIT BRAKE PADS",
      brand: "BOSCH",
      partNumber: "BP-ACC-001",
      price: 850.00,
      mrp: 1100.00,
      discount: 23,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "OEM (genuine)",
      deliveryDays: 4,
    },
    {
      id: 2,
      name: "ACCESSORY KIT BRAKE SHOES",
      brand: "BREMBO",
      partNumber: "BS-ACC-002",
      price: 650.00,
      mrp: 850.00,
      discount: 24,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Mumbai/MUM",
      origin: "OEM (genuine)",
      deliveryDays: 3,
    },
    {
      id: 3,
      name: "ANTI LOCK BRAKING SYSTEM",
      brand: "BOSCH",
      partNumber: "ABS-003",
      price: 8500.00,
      mrp: 10500.00,
      discount: 19,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "OEM (genuine)",
      deliveryDays: 5,
    },
    {
      id: 4,
      name: "BRAKE BOOSTER",
      brand: "DELPHI",
      partNumber: "BB-004",
      price: 3200.00,
      mrp: 4000.00,
      discount: 20,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Delhi/DEL",
      origin: "Aftermarket",
      deliveryDays: 4,
    },
    {
      id: 5,
      name: "BRAKE CABLE",
      brand: "LUCAS",
      partNumber: "BC-005",
      price: 450.00,
      mrp: 600.00,
      discount: 25,
      isOEM: false,
      fulfilledBySparelo: false,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Pune/SWA",
      origin: "Aftermarket",
      deliveryDays: 3,
    },
    {
      id: 6,
      name: "BRAKE CALIPER",
      brand: "BREMBO",
      partNumber: "BCAL-006",
      price: 4500.00,
      mrp: 5500.00,
      discount: 18,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "OEM (genuine)",
      deliveryDays: 4,
    },
    {
      id: 7,
      name: "BRAKE CALIPER PISTON",
      brand: "BOSCH",
      partNumber: "BCP-007",
      price: 1200.00,
      mrp: 1500.00,
      discount: 20,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Mumbai/MUM",
      origin: "OEM (genuine)",
      deliveryDays: 3,
    },
    {
      id: 8,
      name: "BRAKE CALIPER REPAIR KIT",
      brand: "DELPHI",
      partNumber: "BCRK-008",
      price: 550.00,
      mrp: 750.00,
      discount: 27,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "Aftermarket",
      deliveryDays: 4,
    },
    {
      id: 9,
      name: "BRAKE DISC",
      brand: "ZURICH",
      partNumber: "BD-009",
      price: 2500.00,
      mrp: 3000.00,
      discount: 17,
      isOEM: false,
      fulfilledBySparelo: false,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Delhi/DEL",
      origin: "Aftermarket",
      deliveryDays: 5,
    },
    {
      id: 10,
      name: "BRAKE DISC BACK PLATE",
      brand: "LUCAS",
      partNumber: "BDBP-010",
      price: 850.00,
      mrp: 1100.00,
      discount: 23,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Pune/SWA",
      origin: "Aftermarket",
      deliveryDays: 4,
    },
    {
      id: 11,
      name: "BRAKE DISC BOLT",
      brand: "BOSCH",
      partNumber: "BDB-011",
      price: 150.00,
      mrp: 200.00,
      discount: 25,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "OEM (genuine)",
      deliveryDays: 3,
    },
    {
      id: 12,
      name: "BRAKE DRUM BACK PLATE",
      brand: "BREMBO",
      partNumber: "BDRBP-012",
      price: 1200.00,
      mrp: 1500.00,
      discount: 20,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Mumbai/MUM",
      origin: "OEM (genuine)",
      deliveryDays: 4,
    },
    {
      id: 13,
      name: "BRAKE FLUID BOTTLE",
      brand: "BOSCH",
      partNumber: "BFB-013",
      price: 350.00,
      mrp: 450.00,
      discount: 22,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "Aftermarket",
      deliveryDays: 2,
    },
    {
      id: 14,
      name: "BRAKE FLUID RESERVOIR",
      brand: "DELPHI",
      partNumber: "BFR-014",
      price: 450.00,
      mrp: 600.00,
      discount: 25,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Delhi/DEL",
      origin: "Aftermarket",
      deliveryDays: 3,
    },
    {
      id: 15,
      name: "BRAKE HOSES/LINES",
      brand: "LUCAS",
      partNumber: "BHL-015",
      price: 650.00,
      mrp: 850.00,
      discount: 24,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Pune/SWA",
      origin: "Aftermarket",
      deliveryDays: 4,
    },
    {
      id: 16,
      name: "BRAKE LINE JUNCTION",
      brand: "BOSCH",
      partNumber: "BLJ-016",
      price: 550.00,
      mrp: 700.00,
      discount: 21,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: false,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: false,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "OEM (genuine)",
      deliveryDays: 3,
    },
    {
      id: 17,
      name: "BRAKE SENSOR",
      brand: "BREMBO",
      partNumber: "BS-017",
      price: 850.00,
      mrp: 1100.00,
      discount: 23,
      isOEM: true,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Mumbai/MUM",
      origin: "OEM (genuine)",
      deliveryDays: 4,
    },
    {
      id: 18,
      name: "BRAKE MASTER CYLINDER ASSEMBLY",
      brand: "DELPHI",
      partNumber: "BMCA-018",
      price: 3200.00,
      mrp: 4000.00,
      discount: 20,
      isOEM: false,
      fulfilledBySparelo: true,
      freeDelivery: true,
      image: "https://boodmo.com/media/cache/catalog_image/images/categories/437bfd0.jpg",
      spareloChoice: true,
      class: "Brake",
      soldBy: "Bengaluru/BPN",
      origin: "Aftermarket",
      deliveryDays: 5,
    },
  ];

  // Category data for workflow
  const categoryData = {
    name: "Brake System",
    slug: "brakes",
  };

  return (
    <CategoryProductList
      categoryName="Brake System"
      categorySlug="brakes"
      products={products}
      defaultFilters={categoryData}
    />
  );
};

export default BrakeParts;

